openapi: 3.0.0
info:
  title: My API (Loaded from YAML file)
  version: 1.0.0
paths:
  /hello:
    get:
      summary: Returns a greeting
      responses:
        "200":
          description: A successful response
